version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.10.0
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.21.1
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
  vocab-fetch:
    build: ./services/vocab-fetch
    volumes:
      - ./data/vocab-fetch:/share
      - ./services/vocab-fetch/:/app
    environment:
      MODE: "development"
      LOG_LEVEL: "DEBUG"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/public"